blank_issues_enabled: false
contact_links:
  - name: Email Us
    url: mailto:lumen.myllyniemi@gmail.com
    about: For general inquiries, consulting, or anything not covered above.
  - name: SuperLumen
    url: https://superlumen.vercel.app/
    about: Visit our homepage for more information.
